is these complete workflow file is it able to push the code in specific public_html/itme..name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Test SSH connection
        run: |
          ssh -i id_rsa \
            -o StrictHostKeyChecking=no \
            -o BatchMode=yes \
            -o IdentitiesOnly=yes \
            ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} "echo ✅ SSH Connected"

      - name: Deploy via lftp
        run: |
          set -e
          echo "Starting lftp deploy to ${{ secrets.SFTP_HOST }}:$REMOTE_PATH"
          CONNECT_PROG="ssh -a -x -i $PWD/id_rsa -o StrictHostKeyChecking=no -o BatchMode=yes -o IdentitiesOnly=yes"
          lftp -e "set sftp:connect-program '$CONNECT_PROG'; \
                   open sftp://${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}; \
                   mkdir -p $REMOTE_PATH; \
                   mirror -R --parallel=3 --only-newer --verbose build/ $REMOTE_PATH; bye" sftp://${{ secrets.SFTP_HOST }}
          echo "✅ Deployment complete"
        env:
          REMOTE_PATH: public_html/itme.krmangalam.edu.in
