name: Deploy via rsync over SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Test SSH connection
        run: |
          ssh -i id_rsa -o StrictHostKeyChecking=no ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} "echo SSH Connected"

      - name: Deploy via rsync (no delete)
        run: |
          rsync -avz -e "ssh -i id_rsa -o StrictHostKeyChecking=no" build/ ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:public_html/itme.krmangalam.edu.in/
