name: Build and Deploy (cPanel SFTP)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install --no-audit --no-fund
      
      - name: Build project
        run: npm run build
        env:
          CI: false
      
      - name: Archive production artifact
        if: success()
        run: |
          tar -czf build-artifact.tgz build
      
      - name: Upload artifact (debug/re-run support)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build-artifact.tgz
          retention-days: 3
      
      - name: SFTP Deploy to cPanel
        # Using scp (SSH) to push build contents. The previous failure was caused by missing TERM (tput warning).
        # We set TERM to silence the error and adjust source so only the *contents* of build are deployed.
        uses: appleboy/scp-action@v0.1.7
        env:
          TERM: xterm
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 22
          # Copy contents (files & folders) inside build rather than nesting an extra build/ folder remotely
          source: "build/*"
          target: "public_html/itme.krmangalam.edu.in/"
          overwrite: true
          # If you want to remove files on the server that no longer exist locally, uncomment below (be cautious!)
          # rm: true
      
      - name: Post-deploy confirmation
        run: echo "Deployment finished at $(date -u)"
