name: Build and Deploy (cPanel SFTP)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install --no-audit --no-fund
      
      - name: Build project
        run: npm run build
        env:
          CI: false
      
      - name: Archive production artifact
        if: success()
        run: |
          tar -czf build-artifact.tgz build
      
      - name: Upload artifact (debug/re-run support)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build-artifact.tgz
          retention-days: 3
      
      - name: Prepare SSH key for SFTP
        id: prep-key
        run: |
          echo "Writing private key"
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > sftp_key
          chmod 600 sftp_key
          ls -l sftp_key
      
      - name: Install lftp
        run: |
          sudo apt-get update -y
          sudo apt-get install -y lftp
      
      - name: Deploy via lftp (SFTP mirror)
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          REMOTE_PATH: public_html/itme.krmangalam.edu.in
        run: |
          set -e
          echo "Starting lftp deploy to $SFTP_HOST:$REMOTE_PATH"
          # Build a connect program that uses our key and skips strict host checking (add known_hosts later if desired)
          CONNECT_PROG="ssh -a -x -i sftp_key -o StrictHostKeyChecking=no"
          # Mirror options:
          #  -R : reverse mirror (local -> remote)
          #  --parallel=4 : upload up to 4 files simultaneously
          #  --verbose : show progress
          #  --delete : remove remote files not present locally (DISABLED by default for safety)
          DELETE_FLAG=""
          if [ "${{ vars.REMOTE_DELETE }}" = "true" ]; then
            DELETE_FLAG="--delete"
            echo "[INFO] Remote pruning ENABLED"
          else
            echo "[INFO] Remote pruning disabled (vars.REMOTE_DELETE != true)"
          fi
          # Ensure remote path exists (mkdir -p style) then mirror build contents
          lftp -u "$SFTP_USERNAME" sftp://$SFTP_HOST -e "set sftp:connect-program '$CONNECT_PROG'; set net:max-retries 2; set net:timeout 20; set net:persist-retries 1; set ftp:ssl-allow no; mkdir -p $REMOTE_PATH; bye"
          echo "Pushing build directory via mirror"
          lftp -u "$SFTP_USERNAME" sftp://$SFTP_HOST -e "set sftp:connect-program '$CONNECT_PROG'; set net:max-retries 2; set net:timeout 30; set net:persist-retries 1; mirror -R --parallel=4 --only-newer --verbose $DELETE_FLAG build/ $REMOTE_PATH; bye"
          echo "Deployment complete"
      
      - name: List remote top-level (debug)
        if: always()
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        run: |
          CONNECT_PROG="ssh -a -x -i sftp_key -o StrictHostKeyChecking=no"
          echo "Listing remote path snippet for verification" || true
          lftp -u "$SFTP_USERNAME" sftp://$SFTP_HOST -e "set sftp:connect-program '$CONNECT_PROG'; ls -1 public_html/itme.krmangalam.edu.in | head -20; bye" || true
      
      - name: Post-deploy confirmation
        run: echo "Deployment finished at $(date -u)"
